# Generated by Django 3.2.18 on 2023-03-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='amount',
            field=models.IntegerField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery/'),
        ),
    ]
