# Generated by Django 3.2.18 on 2023-03-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20230307_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
