# Generated by Django 3.2.18 on 2023-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_donor_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='monthlyIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
